#!/bin/bash
MAVEN=$(which mvn)
if [ ! -f "$MAVEN" ]; then
  echo "[*] Cannot find maven" && exit 0
fi
echo "[1] Building Artifacts"
echo "" >maven.log
mvn -B package --file pom.xml -Dmaven.compile.fork=true -T 128C
echo "[2] Build Success"
rm -rd out
mkdir out
# shellcheck disable=SC2061
find ./* -type f -name optional-*.jar -exec cp -r {} ./out/ \; 2>/dev/null >/dev/null
cp ./nukkit-support/target/nukkit-support-1.0-SNAPSHOT.jar ./out
echo "[3] Copy Artifacts Success"
find . -type dir -name target -exec rm -dr {} \; >/dev/null 2>/dev/null
echo "[*] Clean target directory Success"
