#!/bin/bash
MAVEN=$(which mvn)
if [ ! -f "$MAVEN" ]; then
  echo "[*] Cannot find maven" && exit 1
fi
echo "[1] Building Artifacts"
mvn -B package --file pom.xml -Dmaven.compile.fork=true -T 128C
echo "[2] Build Success"
rm -rd out
mkdir out
# shellcheck disable=SC2061
find ./* -type f -name optional-*.jar -exec cp -r {} ./out/ \; 2>/dev/null >/dev/null
cp ./nukkit-support/target/nukkit-support-*.jar ./out
cp ./blocklynukkit/target/blocklynukkit-*.jar ./out
cp ./mirai-client/target/mirai-client-*.jar ./out
echo "[3] Copy Artifacts Success"
mvn -B clean --file pom.xml -Dmaven.compile.fork=true -T 128C
echo "[*] Clean target directory Success"
