name: BlocklyNukkit
main: BlocklyNukkit
version: "0.0.1"
author: "?"
api: [ "1.0.8" ]
description: JSE_BlocklyNukkit
load: POSTWORLD
softdepend:
  - PlaceholderAPI
  - EconomyAPI
  - ScoreboardPlugin
  - FakeInventories
  - Tips
  - GameAPI